{% set name = "core" %}
{% set pkg_name = "scine-" + name %}
{% set version = "4.0.1" %}

package:
  name: {{ pkg_name }}
  version: {{ version }}

source:
  - url: https://github.com/qcscine/core/archive/refs/tags/{{ version }}.tar.gz
    sha256: 330a706945200513aa666200b1a0ba8aa38f50ea6aa1abcbad2940cfb7628bb1
    fn: {{ name }}.tar.gz
  - url: https://github.com/qcscine/development-utils/archive/refs/tags/4.0.0.tar.gz
    sha256: 54002c2082b6bb75672ec66bf9cf3935bbdf6b085ed9b4d7174cbdedb7c2275d
    fn: dev.tar.gz
    folder: dev

build:
  number: 0
  skip: true  # [win]
  script:
    - set -ex  # [unix]
    - >
      cmake ${CMAKE_ARGS}  # [unix] -DCMAKE_INSTALL_PREFIX=%LIBRARY_PREFIX%  # [win] -B _build -G Ninja -DSCINE_MARCH=""
    - cmake --build _build
    - ctest --test-dir _build --output-on-failure  # [build_platform == target_platform]
    - cmake --install _build

  run_exports:
    - {{ pin_subpackage(pkg_name, max_pin='x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - ninja
    - pkg-config
    - llvm-openmp  # [osx]
    - libgomp  # [linux]
  host:
    - gtest
    - gmock
    - boost-cpp
  run:
    - boost-cpp

test:
  commands:
    - test -f $PREFIX/lib/lib{{ name }}${SHLIB_EXT}  # [unix]
    - if not exist %LIBRARY_PREFIX%\lib\{{ name }}.dll exit 1  # [win]

about:
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: |
    Core provides the functionality necessary to couple the individual SCINE modules together.
  home: https://scine.ethz.ch/
  dev_url: https://github.com/qcscine/core

extra:
  recipe-maintainers:
    - awvwgk
